_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 14
                - 17
                - 23
                - 55
            "4": 3.11.4
            "5": 0.19.11
            "8":
                - 3
                - 5
            "10":
                - 3
            "12": 0.19.11
            "13": windows-amd64
beam_search:
    value: 1
cell_type:
    value: LSTM
dropout:
    value: 0.3
embedding_dim:
    value: 64
epochs:
    value: 5
hidden_size:
    value: 256
max_len:
    value: 30
num_layers:
    value: 3
