wandb_version: 1

beam_search:
  value: 1
cell_type:
  value: GRU
dropout:
  value: 0.25
embedding_dim:
  value: 256
epochs:
  value: 5
hidden_size:
  value: 256
max_len:
  value: 30
num_layers:
  value: 2
