wandb_version: 1

beam_search:
  value: 1
cell_type:
  value: LSTM
dropout:
  value: 0.3
embedding_dim:
  value: 64
epochs:
  value: 5
hidden_size:
  value: 128
max_len:
  value: 30
num_layers:
  value: 3
